#!/usr/bin/env bash
# Regenerate the "What it checks" table in README.md from the preflight manifest.
#
# The CHECKS manifest in preflight.sh is the single source of truth; this script
# renders it into the marked block in README.md. Run it after changing the
# manifest. CI runs it too and fails if README.md ends up modified (see
# .github/workflows/ci.yml), so the docs can never silently drift.

set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
readme="$here/../README.md"
begin="<!-- BEGIN CHECKS TABLE (generated by scripts/preflight.sh --list — do not edit) -->"
end="<!-- END CHECKS TABLE -->"

# Render the table to a temp file. We feed awk the *filename* (a single-line
# value) and let it read the multi-line table via getline — passing a multi-line
# string through `awk -v` is rejected by BSD awk (macOS).
tbl="$(mktemp)"
trap 'rm -f "$tbl"' EXIT
bash "$here/preflight.sh" --list > "$tbl"

awk -v b="$begin" -v e="$end" -v tf="$tbl" '
  $0 == b { print; while ((getline line < tf) > 0) print line; close(tf); skip = 1; next }
  $0 == e { skip = 0 }
  skip   { next }
  { print }
' "$readme" > "$readme.tmp"
mv "$readme.tmp" "$readme"

echo "README.md checks table regenerated from the manifest."
